/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ZenBook
 */
public class Equipamiento extends javax.swing.JPanel {

    /**
     * Creates new form Inventario
     */
    public Equipamiento() {

        initComponents();
        this.btnHerramientas.setSelected(true);
        
        herramientas h = new herramientas();
        h.setSize(890,690 );
        h.setLocation(0,0);
        
        panelprinicpal.removeAll();
        panelprinicpal.add(h, BorderLayout.CENTER);
        panelprinicpal.revalidate();
        panelprinicpal.repaint();
      
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        btnHerramientas = new rojeru_san.RSButtonRiple();
        btnMaquinaria = new rojeru_san.RSButtonRiple();
        btnNuevo = new rojeru_san.RSButtonRiple();
        panelprinicpal = new javax.swing.JPanel();

        setBackground(new java.awt.Color(228, 233, 247));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(32767, 32));
        setPreferredSize(new java.awt.Dimension(1200, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorIcon(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        txtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscar.setPhColor(new java.awt.Color(102, 102, 102));
        txtBuscar.setPlaceholder("Buscar...");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 357, 30));

        btnHerramientas.setBackground(new java.awt.Color(0, 0, 0));
        btnHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wrench.png"))); // NOI18N
        btnHerramientas.setText("  Herramientas");
        btnHerramientas.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHerramientasActionPerformed(evt);
            }
        });
        add(btnHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, -1));

        btnMaquinaria.setBackground(new java.awt.Color(0, 0, 0));
        btnMaquinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gears-set.png"))); // NOI18N
        btnMaquinaria.setText("  Maquinaria");
        btnMaquinaria.setToolTipText("");
        btnMaquinaria.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnMaquinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquinariaActionPerformed(evt);
            }
        });
        add(btnMaquinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 210, -1));

        btnNuevo.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo.setText(" Nuevo");
        btnNuevo.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 110, 30));

        panelprinicpal.setBackground(new java.awt.Color(228, 233, 247));
        panelprinicpal.setPreferredSize(new java.awt.Dimension(1000, 490));
        add(panelprinicpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 950, 520));
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHerramientasActionPerformed
    if(!this.btnHerramientas.isSelected()) {
    this.btnHerramientas.setSelected(true);   
      this.btnMaquinaria.setSelected(false);
      
        herramientas h = new herramientas();
        h.setSize(890,690 );
        h.setLocation(0,0);
        
        panelprinicpal.removeAll();
        panelprinicpal.add(h);
        panelprinicpal.revalidate();
        panelprinicpal.repaint();

         }
    }//GEN-LAST:event_btnHerramientasActionPerformed

    private void btnMaquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquinariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquinariaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnHerramientas;
    private rojeru_san.RSButtonRiple btnMaquinaria;
    private rojeru_san.RSButtonRiple btnNuevo;
    private javax.swing.JPanel panelprinicpal;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscar;
    // End of variables declaration//GEN-END:variables


}

