/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ZenBook
 */
public class Inventario extends javax.swing.JPanel {

    /**
     * Creates new form Inventario
     */
    public Inventario() {

        initComponents();
        this.btnMateriales.setSelected(true);
        
        materiales es = new materiales();
        es.setSize(1000, 490);
        es.setLocation(0,0);
        
        panelprincipal.removeAll();
        panelprincipal.add(es, BorderLayout.CENTER);
        panelprincipal.revalidate();
        panelprincipal.repaint();
      
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMateriales = new rojeru_san.RSButtonRiple();
        btnProductos = new rojeru_san.RSButtonRiple();
        btnMovimientos = new rojeru_san.RSButtonRiple();
        panelprincipal = new javax.swing.JPanel();

        setBackground(new java.awt.Color(228, 233, 247));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(32767, 32));
        setPreferredSize(new java.awt.Dimension(1015, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMateriales.setBackground(new java.awt.Color(0, 0, 0));
        btnMateriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/box.png"))); // NOI18N
        btnMateriales.setText("  Materiales");
        btnMateriales.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialesActionPerformed(evt);
            }
        });
        add(btnMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 40));

        btnProductos.setBackground(new java.awt.Color(0, 0, 0));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tienda-de-comestibles.png"))); // NOI18N
        btnProductos.setText("  Productos terminados");
        btnProductos.setToolTipText("");
        btnProductos.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 250, -1));

        btnMovimientos.setBackground(new java.awt.Color(0, 0, 0));
        btnMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transfer.png"))); // NOI18N
        btnMovimientos.setText("  Movimientos");
        btnMovimientos.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        btnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosActionPerformed(evt);
            }
        });
        add(btnMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 210, -1));

        panelprincipal.setBackground(new java.awt.Color(228, 233, 247));
        panelprincipal.setPreferredSize(new java.awt.Dimension(960, 570));
        add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 960, 570));
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialesActionPerformed
        // TODO add your handling code here:
         if(!this.btnMateriales.isSelected()) {
    this.btnMateriales.setSelected(true);   
      this.btnProductos.setSelected(false);
      this.btnMovimientos.setSelected(false);
        
        materiales es = new materiales();
        es.setSize(1000, 490);
        es.setLocation(0,0);
        
        panelprincipal.removeAll();
        panelprincipal.add(es);
        panelprincipal.revalidate();
        panelprincipal.repaint();

         }
    }//GEN-LAST:event_btnMaterialesActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovimientosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnMateriales;
    private rojeru_san.RSButtonRiple btnMovimientos;
    private rojeru_san.RSButtonRiple btnProductos;
    private javax.swing.JPanel panelprincipal;
    // End of variables declaration//GEN-END:variables


}

