/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author ZenBook
 */
public class materiales extends javax.swing.JPanel {

    /**
     * Creates new form materiales
     */
    public materiales() {
        initComponents();
        
        setLayout(new GridLayout(0, 1, 10, 10)); // Diseño de tarjetas en columnas
    }

        // Método para agregar una nueva tarjeta
    public void agregarTarjeta(String codigo, String nombre, String descripcion, String categoria, 
                               String unidad, int cantidad, String proveedor, ImageIcon imagen) {
        JPanel tarjeta = new JPanel();
        tarjeta.setLayout(new BoxLayout(tarjeta, BoxLayout.Y_AXIS));
        tarjeta.setBorder(BorderFactory.createTitledBorder(nombre));

        JLabel lblCodigo = new JLabel("Código: " + codigo);
        JLabel lblDescripcion = new JLabel("Descripción: " + descripcion);
        JLabel lblCategoria = new JLabel("Categoría: " + categoria);
        JLabel lblUnidad = new JLabel("Unidad: " + unidad);
        JLabel lblCantidad = new JLabel("Cantidad: " + cantidad);
        JLabel lblProveedor = new JLabel("Proveedor: " + proveedor);
        JLabel lblImagen = new JLabel(imagen);

        tarjeta.add(lblCodigo);
        tarjeta.add(lblDescripcion);
        tarjeta.add(lblCategoria);
        tarjeta.add(lblUnidad);
        tarjeta.add(lblCantidad);
        tarjeta.add(lblProveedor);
        tarjeta.add(lblImagen);

        add(tarjeta);
        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal = new javax.swing.JPanel();
        txtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        btnNuevo = new rojeru_san.RSButtonRiple();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        rSButtonRiple3 = new rojeru_san.RSButtonRiple();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rSButtonRiple10 = new rojeru_san.RSButtonRiple();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rSButtonRiple11 = new rojeru_san.RSButtonRiple();
        rSButtonRiple12 = new rojeru_san.RSButtonRiple();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        rSButtonRiple13 = new rojeru_san.RSButtonRiple();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rSButtonRiple14 = new rojeru_san.RSButtonRiple();
        rSButtonRiple15 = new rojeru_san.RSButtonRiple();
        panelTargetas = new javax.swing.JPanel();
        rSComboBox1 = new RSMaterialComponent.RSComboBox();

        setPreferredSize(new java.awt.Dimension(960, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setBackground(new java.awt.Color(228, 233, 247));
        panelprincipal.setPreferredSize(new java.awt.Dimension(960, 570));
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorIcon(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        txtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscar.setPhColor(new java.awt.Color(102, 102, 102));
        txtBuscar.setPlaceholder("Buscar...");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panelprincipal.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        btnNuevo.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo.setText(" Nuevo");
        btnNuevo.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        panelprincipal.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 110, 30));

        jPanel1.setBackground(new java.awt.Color(46, 49, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mdfimg.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

        rSButtonRiple1.setBackground(new java.awt.Color(255, 0, 51));
        rSButtonRiple1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete (1).png"))); // NOI18N
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 40, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Categoria: Madera");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo: 101");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre: Mdf");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        rSButtonRiple2.setBackground(new java.awt.Color(0, 204, 102));
        rSButtonRiple2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye (1).png"))); // NOI18N
        rSButtonRiple2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 40, 20));

        rSButtonRiple3.setBackground(new java.awt.Color(0, 153, 255));
        rSButtonRiple3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil (1)_1.png"))); // NOI18N
        rSButtonRiple3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonRiple3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 40, 20));

        panelprincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 300));

        jPanel4.setBackground(new java.awt.Color(46, 49, 82));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pega-madera-40 (2).jpg"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

        rSButtonRiple10.setBackground(new java.awt.Color(255, 0, 51));
        rSButtonRiple10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete (1).png"))); // NOI18N
        rSButtonRiple10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple10ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonRiple10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 40, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Categoria: Madera");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Codigo: 101");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nombre: Mdf");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        rSButtonRiple11.setBackground(new java.awt.Color(0, 204, 102));
        rSButtonRiple11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye (1).png"))); // NOI18N
        rSButtonRiple11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple11ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonRiple11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 40, 20));

        rSButtonRiple12.setBackground(new java.awt.Color(0, 153, 255));
        rSButtonRiple12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil (1)_1.png"))); // NOI18N
        rSButtonRiple12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple12ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonRiple12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 40, 20));

        panelprincipal.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 210, 300));

        jPanel5.setBackground(new java.awt.Color(46, 49, 82));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clavos (3).jpeg"))); // NOI18N
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 240, 170));

        rSButtonRiple13.setBackground(new java.awt.Color(255, 0, 51));
        rSButtonRiple13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete (1).png"))); // NOI18N
        rSButtonRiple13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple13ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonRiple13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 40, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Categoria: Madera");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Codigo: 101");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nombre: Mdf");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        rSButtonRiple14.setBackground(new java.awt.Color(0, 204, 102));
        rSButtonRiple14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye (1).png"))); // NOI18N
        rSButtonRiple14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple14ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonRiple14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 40, 20));

        rSButtonRiple15.setBackground(new java.awt.Color(0, 153, 255));
        rSButtonRiple15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil (1)_1.png"))); // NOI18N
        rSButtonRiple15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple15ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonRiple15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 40, 20));

        panelprincipal.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 210, 300));

        panelTargetas.setBackground(new java.awt.Color(46, 49, 82));
        panelprincipal.add(panelTargetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 210, 300));

        rSComboBox1.setColorArrow(new java.awt.Color(46, 49, 82));
        rSComboBox1.setColorBorde(new java.awt.Color(46, 49, 82));
        rSComboBox1.setColorFondo(new java.awt.Color(46, 49, 82));
        rSComboBox1.setColorSeleccion(new java.awt.Color(46, 49, 82));
        rSComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSComboBox1ActionPerformed(evt);
            }
        });
        panelprincipal.add(rSComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 160, 30));

        add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    private void rSButtonRiple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple2ActionPerformed

    private void rSButtonRiple3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple3ActionPerformed

    private void rSButtonRiple10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple10ActionPerformed

    private void rSButtonRiple11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple11ActionPerformed

    private void rSButtonRiple12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple12ActionPerformed

    private void rSButtonRiple13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple13ActionPerformed

    private void rSButtonRiple14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple14ActionPerformed

    private void rSButtonRiple15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRiple15ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevoMateriales dialog = new nuevoMateriales(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null); // Centra la ventana emergente
        dialog.setVisible(true); // Muestra la ventana
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void rSComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelTargetas;
    private javax.swing.JPanel panelprincipal;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSButtonRiple rSButtonRiple10;
    private rojeru_san.RSButtonRiple rSButtonRiple11;
    private rojeru_san.RSButtonRiple rSButtonRiple12;
    private rojeru_san.RSButtonRiple rSButtonRiple13;
    private rojeru_san.RSButtonRiple rSButtonRiple14;
    private rojeru_san.RSButtonRiple rSButtonRiple15;
    private rojeru_san.RSButtonRiple rSButtonRiple2;
    private rojeru_san.RSButtonRiple rSButtonRiple3;
    private RSMaterialComponent.RSComboBox rSComboBox1;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscar;
    // End of variables declaration//GEN-END:variables
}
